
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: prathibha
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  employee-app:
    build: .
    container_name: employee-container
    depends_on:
      - mysql
    ports:
      - "8081:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data: